---
github_output_directory: .github/workflows

github_runs_on: self-hosted

github_registry_url: ghcr.io

github_registry_username: ${{ github.actor }}

github_registry_password: ${{ secrets.GITHUB_TOKEN }}

github_image_name: ${{ github.repository }}:latest

github_kayobe_arguments: {}

github_checkout_hook: ""

github_kayobe_hook: ""

github_final_hook: ""

github_kayobe_inputs: &github_kayobe_inputs
  kayobeLimit:
    description: |
      The ansible limit to use when running kayobe playbooks.
  kayobeTags:
    description: |
      The ansible tags to use when running kayobe playbooks.

github_kolla_inputs: &github_kolla_inputs
  kollaLimit:
    description: |
      The ansible limit to use for kolla-ansible playbooks.
  kollaTags:
    description: |
      The ansible tags to use when running kolla-ansible playbooks.

github_combined_inputs: &github_combined_inputs
  <<: [*github_kayobe_inputs, *github_kolla_inputs]

github_workflows:
  - "{{ github_build_kayobe_image }}"
  - "{{ github_run_kolla_config_diff }}"
  - "{{ github_run_infra_vm_host_configure }}"
  - "{{ github_run_infra_vm_host_package_update }}"
  - "{{ github_run_infra_vm_provision }}"
  - "{{ github_run_infra_vm_service_deploy }}"
  - "{{ github_run_network_connectivity_check }}"
  - "{{ github_run_overcloud_container_image_pull }}"
  - "{{ github_run_overcloud_database_backup }}"
  - "{{ github_run_overcloud_host_configure }}"
  - "{{ github_run_overcloud_host_package_update }}"
  - "{{ github_run_overcloud_inventory_discover }}"
  - "{{ github_run_overcloud_provision }}"
  - "{{ github_run_overcloud_service_deploy }}"
  - "{{ github_run_overcloud_service_upgrade }}"
  - "{{ github_run_seed_host_configure }}"
  - "{{ github_run_seed_host_package_update }}"
  - "{{ github_run_seed_hypervisor_host_configure }}"
  - "{{ github_run_seed_hypervisor_host_package_update }}"
  - "{{ github_run_seed_service_deploy }}"
  - "{{ github_run_seed_vm_provision }}"
  - "{{ github_run_tempest }}"

github_build_kayobe_image:
  file_name: build-kayobe-docker-image.yml
  use_bespoke: true

github_run_kolla_config_diff:
  file_name: run-config-diff.yml
  use_bespoke: true

github_run_infra_vm_host_configure:
  file_name: run-infra-vm-host-configure.yml
  trigger:
    workflow_dispatch: *github_kayobe_inputs
  arguments:
    - KAYOBE_TAGS
    - KAYOBE_LIMIT
    - HOME

github_run_infra_vm_host_package_update:
  file_name: run-infra-vm-host-package-update.yml
  trigger:
    workflow_dispatch: *github_kayobe_inputs
  arguments:
    - KAYOBE_TAGS
    - KAYOBE_LIMIT
    - HOME

github_run_infra_vm_provision:
  file_name: run-infra-vm-provision.yml
  trigger:
    workflow_dispatch: *github_kayobe_inputs
  arguments:
    - KAYOBE_TAGS
    - KAYOBE_LIMIT
    - HOME

github_run_infra_vm_service_deploy:
  file_name: run-infra-vm-service-deploy.yml
  trigger:
    workflow_dispatch: *github_kayobe_inputs
  arguments:
    - KAYOBE_TAGS
    - KAYOBE_LIMIT
    - HOME

github_run_network_connectivity_check:
  file_name: run-network-connectivity-check.yml
  trigger:
    workflow_dispatch: *github_kayobe_inputs
  arguments:
    - KAYOBE_TAGS
    - KAYOBE_LIMIT
    - HOME

github_run_overcloud_container_image_pull:
  file_name: run-overcloud-container-image-pull.yml
  trigger:
    workflow_dispatch: *github_combined_inputs
  arguments:
    - KOLLA_TAGS
    - KOLLA_LIMIT
    - KAYOBE_TAGS
    - KAYOBE_LIMIT
    - HOME

github_run_overcloud_database_backup:
  file_name: run-overcloud-database-backup.yml
  trigger:
    workflow_dispatch: *github_combined_inputs
  arguments:
    - KOLLA_TAGS
    - KOLLA_LIMIT
    - KAYOBE_TAGS
    - KAYOBE_LIMIT
    - HOME

github_run_overcloud_host_configure:
  file_name: run-overcloud-host-configure.yml
  trigger:
    workflow_dispatch: *github_combined_inputs
  arguments:
    - KOLLA_TAGS
    - KOLLA_LIMIT
    - KAYOBE_TAGS
    - KAYOBE_LIMIT
    - HOME

github_run_overcloud_host_package_update:
  file_name: run-overcloud-host-package-update.yml
  trigger:
    workflow_dispatch: *github_kayobe_inputs
  arguments:
    - KAYOBE_TAGS
    - KAYOBE_LIMIT
    - HOME

github_run_overcloud_inventory_discover:
  file_name: run-overcloud-inventory-discover.yml
  trigger:
    workflow_dispatch: *github_kayobe_inputs
  arguments:
    - KAYOBE_TAGS
    - KAYOBE_LIMIT
    - KAYOBE_AUTOMATION_PR_TARGET_BRANCH
    - KAYOBE_AUTOMATION_PR_REMOTE
    - KAYOBE_AUTOMATION_PR_GITHUB_USER
    - KAYOBE_AUTOMATION_PR_AUTH_TOKEN
    - KAYOBE_AUTOMATION_PR_TYPE
    - KAYOBE_AUTOMATION_PR_TITLE
    - KAYOBE_AUTOMATION_PR_URL
    - HOME

github_run_overcloud_provision:
  file_name: run-overcloud-provision.yml
  trigger:
    workflow_dispatch: *github_kayobe_inputs
  arguments:
    - KAYOBE_TAGS
    - KAYOBE_LIMIT
    - HOME

github_run_overcloud_service_deploy:
  file_name: run-overcloud-service-deploy.yml
  trigger:
    workflow_dispatch: *github_combined_inputs
  arguments:
    - KOLLA_TAGS
    - KOLLA_LIMIT
    - KAYOBE_TAGS
    - KAYOBE_LIMIT
    - KAYOBE_AUTOMATION_PR_TARGET_BRANCH
    - KAYOBE_AUTOMATION_PR_REMOTE
    - KAYOBE_AUTOMATION_PR_GITHUB_USER
    - KAYOBE_AUTOMATION_PR_AUTH_TOKEN
    - KAYOBE_AUTOMATION_PR_TYPE
    - KAYOBE_AUTOMATION_PR_TITLE
    - KAYOBE_AUTOMATION_PR_URL
    - HOME

github_run_overcloud_service_upgrade:
  file_name: run-overcloud-service-upgrade.yml
  trigger:
    workflow_dispatch: *github_combined_inputs
  arguments:
    - KOLLA_TAGS
    - KOLLA_LIMIT
    - KAYOBE_TAGS
    - KAYOBE_LIMIT
    - KAYOBE_AUTOMATION_PR_TARGET_BRANCH
    - KAYOBE_AUTOMATION_PR_REMOTE
    - KAYOBE_AUTOMATION_PR_GITHUB_USER
    - KAYOBE_AUTOMATION_PR_AUTH_TOKEN
    - KAYOBE_AUTOMATION_PR_TYPE
    - KAYOBE_AUTOMATION_PR_TITLE
    - KAYOBE_AUTOMATION_PR_URL
    - HOME

github_run_seed_host_configure:
  file_name: run-seed-host-configure.yml
  trigger:
    workflow_dispatch: *github_combined_inputs
  arguments:
    - KOLLA_TAGS
    - KOLLA_LIMIT
    - KAYOBE_TAGS
    - KAYOBE_LIMIT
    - HOME

github_run_seed_host_package_update:
  file_name: run-seed-host-package-update.yml
  trigger:
    workflow_dispatch: *github_kayobe_inputs
  arguments:
    - KAYOBE_TAGS
    - KAYOBE_LIMIT
    - HOME

github_run_seed_hypervisor_host_configure:
  file_name: run-seed-hypervisor-host-configure.yml
  trigger:
    workflow_dispatch: *github_kayobe_inputs
  arguments:
    - KAYOBE_TAGS
    - KAYOBE_LIMIT
    - HOME

github_run_seed_hypervisor_host_package_update:
  file_name: run-seed-hypervisor-host-package-update.yml
  trigger:
    workflow_dispatch: *github_kayobe_inputs
  arguments:
    - KAYOBE_TAGS
    - KAYOBE_LIMIT
    - HOME

github_run_seed_service_deploy:
  file_name: run-seed-service-deploy.yml
  trigger:
    workflow_dispatch: *github_combined_inputs
  arguments:
    - KOLLA_TAGS
    - KOLLA_LIMIT
    - KAYOBE_TAGS
    - KAYOBE_LIMIT
    - KAYOBE_AUTOMATION_PR_TARGET_BRANCH
    - KAYOBE_AUTOMATION_PR_REMOTE
    - KAYOBE_AUTOMATION_PR_GITHUB_USER
    - KAYOBE_AUTOMATION_PR_AUTH_TOKEN
    - KAYOBE_AUTOMATION_PR_TYPE
    - KAYOBE_AUTOMATION_PR_TITLE
    - KAYOBE_AUTOMATION_PR_URL
    - HOME

github_run_seed_vm_provision:
  file_name: run-seed-vm-provision.yml
  trigger:
    workflow_dispatch: *github_kayobe_inputs
  arguments:
    - KAYOBE_TAGS
    - KAYOBE_LIMIT
    - HOME

github_run_tempest:
  file_name: run-tempest.yml
  use_bespoke: true
