---
github_output_directory: .github/workflows

github_runs_on: self-hosted

github_registry_url: ghcr.io

github_registry_username: ${{ github.actor }}

github_registry_password: ${{ secrets.GITHUB_TOKEN }}

github_image_name: ${{ github.repository }}:latest

github_kayobe_arguments: {}

github_kayobe_inputs: &github_kayobe_inputs
  kayobeLimit:
    description: |
      The ansible limit to use when running kayobe playbooks.
  kayobeTags:
    description: |
      The ansible tags to use when running kayobe playbooks.

github_kolla_inputs: &github_kolla_inputs
  kollaLimit:
    description: |
      The ansible limit to use for kolla-ansible playbooks.
  kollaTags:
    description: |
      The ansible tags to use when running kolla-ansible playbooks.

github_combined_inputs: &github_combined_inputs
  <<: [*github_kayobe_inputs, *github_kolla_inputs]

github_workflows:
  - "{{ build_kayobe_image }}"

build_kayobe_image:
  file_name: build-kayobe-docker-image.yml
  use_bespoke: true
