---
github_default_registry:
  url: ghcr.io
  username: !unsafe "${{ github.actor }}"
  password: !unsafe "${{ secrets.GITHUB_TOKEN }}"
  share: false

github_default_kayobe_arguments:
  KAYOBE_VAULT_PASSWORD: !unsafe "${{ secrets.KAYOBE_VAULT_PASSWORD }}"
  KAYOBE_AUTOMATION_SSH_PRIVATE_KEY: !unsafe "${{ secrets.KAYOBE_AUTOMATION_SSH_PRIVATE_KEY }}"
  KOLLA_LIMIT: !unsafe "${{ github.event.inputs.kolla_limit }}"
  KOLLA_TAGS: !unsafe "${{ github.event.inputs.kolla_tags }}"
  KAYOBE_TAGS: !unsafe "${{ github.event.inputs.kayobe_tags }}"
  KAYOBE_LIMIT: !unsafe "${{ github.event.inputs.kayobe_limit }}"
  KAYOBE_AUTOMATION_PR_TARGET_BRANCH: !unsafe ${{ github.event.ref }}
  KAYOBE_AUTOMATION_PR_REMOTE: !unsafe https://${KAYOBE_AUTOMATION_PR_GITHUB_USER}:${KAYOBE_AUTOMATION_PR_AUTH_TOKEN}@github.com/${{ github.repository }}
  KAYOBE_AUTOMATION_PR_GITHUB_USER: !unsafe ${{ github.actor }}
  KAYOBE_AUTOMATION_PR_AUTH_TOKEN: !unsafe ${{ github.token }}
  KAYOBE_AUTOMATION_PR_TYPE: github
  KAYOBE_AUTOMATION_PR_TITLE: !unsafe "[kayobe-automation] ${{ github.workflow }} #${{ github.run_id }}"
  KAYOBE_AUTOMATION_PR_URL: !unsafe https://api.github.com/repos/${{ github.repository }}/pulls
  KAYOBE_AUTOMATION_TEMPEST_LOADLIST: !unsafe "${{ github.event.inputs.test_suite }}"
  TEMPEST_PATTERN: !unsafe "${{ github.event.inputs.tempest_pattern }}"
  TEMPEST_OPENRC: !unsafe "${{ secrets.TEMPEST_OPENRC }}"
  HOME: /stack

github_kayobe_dispatch_inputs:
  - "{{ github_kayobe_limit_input }}"
  - "{{ github_kayobe_tags_input }}"

github_kolla_dispatch_inputs:
  - "{{ github_kolla_tags_input }}"
  - "{{ github_kolla_limit_input }}"

github_kayobe_task_arguments:
  - KAYOBE_TAGS
  - KAYOBE_LIMIT

github_kolla_task_arguments:
  - KOLLA_TAGS
  - KOLLA_LIMIT

github_kayobe_pull_request_arguments:
  - KAYOBE_AUTOMATION_PR_TARGET_BRANCH
  - KAYOBE_AUTOMATION_PR_REMOTE
  - KAYOBE_AUTOMATION_PR_GITHUB_USER
  - KAYOBE_AUTOMATION_PR_AUTH_TOKEN
  - KAYOBE_AUTOMATION_PR_TYPE
  - KAYOBE_AUTOMATION_PR_TITLE
  - KAYOBE_AUTOMATION_PR_URL
