---
github_default_registry:
  url: !unsafe "${{ vars.REGISTRY_URL }}"
  username: !unsafe "${{ vars.REGISTRY_USERNAME }}"
  password: !unsafe "${{ secrets.REGISTRY_PASSWORD }}"
  share: false

github_default_kayobe_arguments:
  KAYOBE_VAULT_PASSWORD: !unsafe "${{ secrets.KAYOBE_VAULT_PASSWORD }}"
  KAYOBE_AUTOMATION_SSH_PRIVATE_KEY: !unsafe "${{ secrets.KAYOBE_AUTOMATION_SSH_PRIVATE_KEY }}"
  KOLLA_LIMIT: !unsafe "${{ github.event.inputs.kolla_limit }}"
  KOLLA_TAGS: !unsafe "${{ github.event.inputs.kolla_tags }}"
  KAYOBE_TAGS: !unsafe "${{ github.event.inputs.kayobe_tags }}"
  KAYOBE_LIMIT: !unsafe "${{ github.event.inputs.kayobe_limit }}"
  KAYOBE_AUTOMATION_PR_TARGET_BRANCH: !unsafe ${{ github.event.ref }}
  KAYOBE_AUTOMATION_PR_REMOTE: !unsafe https://${KAYOBE_AUTOMATION_PR_GITHUB_USER}:${KAYOBE_AUTOMATION_PR_AUTH_TOKEN}@github.com/${{ github.repository }}
  KAYOBE_AUTOMATION_PR_GITHUB_USER: !unsafe ${{ github.actor }}
  KAYOBE_AUTOMATION_PR_AUTH_TOKEN: !unsafe ${{ github.token }}
  KAYOBE_AUTOMATION_PR_TYPE: github
  KAYOBE_AUTOMATION_PR_TITLE: !unsafe "[kayobe-automation] ${{ github.workflow }} #${{ github.run_id }}"
  KAYOBE_AUTOMATION_PR_URL: !unsafe https://api.github.com/repos/${{ github.repository }}/pulls
  KAYOBE_AUTOMATION_TEMPEST_LOADLIST: !unsafe "${{ inputs.run_previous_failed == false && github.event.inputs.test_suite || 'previous-failed-tests' }}"
  TEMPEST_PATTERN: !unsafe "${{ github.event.inputs.tempest_pattern }}"
  TEMPEST_OPENRC: !unsafe "${{ secrets.TEMPEST_OPENRC }}"
  HOME: /stack

github_kayobe_dispatch_inputs:
  - "{{ github_kayobe_limit_input }}"
  - "{{ github_kayobe_tags_input }}"

github_kolla_dispatch_inputs:
  - "{{ github_kolla_limit_input }}"
  - "{{ github_kolla_tags_input }}"

github_kayobe_task_arguments:
  - KAYOBE_TAGS
  - KAYOBE_LIMIT

github_kolla_task_arguments:
  - KOLLA_TAGS
  - KOLLA_LIMIT

github_kayobe_pull_request_arguments:
  - KAYOBE_AUTOMATION_PR_TARGET_BRANCH
  - KAYOBE_AUTOMATION_PR_REMOTE
  - KAYOBE_AUTOMATION_PR_GITHUB_USER
  - KAYOBE_AUTOMATION_PR_AUTH_TOKEN
  - KAYOBE_AUTOMATION_PR_TYPE
  - KAYOBE_AUTOMATION_PR_TITLE
  - KAYOBE_AUTOMATION_PR_URL

github_docker_image_version: "27.3.1"
github_actions_checkout_version: "v4.2.0"
github_docker_login_action_version: "v3.3.0"
github_docker_setup_buildx_action_version: "v3.6.1"
github_buildkit_image_version: "v0.16.0"
github_buildx_version: "v0.17.1"
github_docker_build_push_action_version: "v6.7.0"
github_actions_upload_artifact_version: "v4.4.0"
github_actions_github_script_version: "v7.0.1"
github_actions_download_artifact_version: "v4.1.8"
github_mikepenz_action_junit_report_version: "db71d41eb79864e25ab0337e395c352e84523afe" # v4.3.1
